baseURL: "https://sschulver.github.io/"
languageCode: "en-us"
title: "Steph Wever Schulman"
theme: "hugo-profile"



outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: about
#       name: About
#       title: About
#       url: /about
#       weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Steph Wever Schulman"
  description: digital portfolio
  #staticPath: "/Users/swever/sschulver_hugo/static"  # The path to serve the static files from
  favicon: "/S.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Steph Wever Schulman" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Steph."
    subtitle: "I am a self-professed data nerd!"
    content: "I am passionate about making meaningful connections between disperate datasets of all shapes and sizes."
    image: "/steph.png"
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      # enable: true
      # name: "Resume"
      # url: "#"
      # download: true
      # newPage: false
    socialLinks:
      fontAwesomeIcons:
        # - icon: fab fa-github
        #   url: https://example.com
        # - icon: fab fa-twitter
        #   url: https://example.com
      customIcons:
       # - icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    #image: "/steph.png"
    content: |-
        Hey there! I'm a data enthusiast through and through, always seeking out the fascinating realm of scientific data analysis and management. I live and breathe for the thrill of uncovering hidden insights and transforming raw information into meaningful knowledge. Whether it's diving into epidemiological studies, crunching numbers with statistical analysis, or meticulously cleaning data, I'm fueled by the desire to unearth valuable insights that drive informed decision-making.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "R"
        - "Python"
        - "SQL"


  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Scientific Data Specialist"
        company: "University of Pennsylvania"
        companyUrl: "https://www.clinepidb.org"
        date: "March 2020 - present"
        info:
          enable: false
        featuredLink:
          enable: false
          name: 
          url: 
        content: |
         • Championed over six different epidemiological studies ranging in study design from observational to randomized control studies by performing relevant data cleaning, ontological development, and assignment of variables

         • Created relevant study specific example queries and visualizations for use as quality control of data loaded and presented on ClinEpiDB.org

         • Aided in the creation of a new exploratory data analysis tool from initial brainstorming of concepts and features to assessing feature functionality and ease of use

         • Developed and assessed novel techniques for automation of ontological development through natural language processing utilizing Python NLTK tool kit and Solr indexing in R

      - job: "Data Analyst"
        company: "National Board of Medical Examiners"
        companyUrl: "https://www.nbme.org/"
        date: "August 2016 - Marc 2023"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: 
        content: |
          • Mined and manipulated internal and external data to assemble complex datasets/databases in preparation for statistical analysis

          • Created an annotation process used in the development of an automating scoring system of free text using NLP to establish an online annotation environment by querying and sampling exam specific free text responses

          • Conducted and interpreted sophisticated statistical analyses for internal examination programs and external client requests

          • Synthesized results of sophisticated statistical analyses and creating clear and concise summaries/reports used for in-house decision and policy making
          
      - job: "Data Analyst"
        company: "Signant Health"
        companyUrl: "https://www.signanthealth.com/"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          • Authored specifications, programming and maintained code used for data management & validation, ad-hoc reports, data exports, program validation and analytics

          • Assisted internal and external customers such as Client Services (inclusive of project delivery teams and clinical), Technical Delivery and Product Innovation, Science and Medicine, and Business Development functions with the intent of process efficiencies and improvement

          • Communicated effectively within a multi-disciplinary project team to complete assigned tasks on time and within budget
      

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Public Health in Biostatistics & Epidemiology"
        school:
          name: "Drexel University, Dornsife School of Public Health"
          url: "https://drexel.edu/dornsife/"
        date: "2010 - 2012"
        #GPA: 
        content: |-
          <b>Thesis:</b> Psychosocial factors that influencing HPV vaccine uptake among adolescent females in Philadelphia, PA
            
      - title: "Bachelor of Science in Chemistry"
        school:
          name: "Gordon College"
          url: "https://www.gordon.edu"
        date: "2002 - 2006"
        #GPA: 
        content: |-


        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"


  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: 
        content: 
        url: 
      

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"